/* eslint-disable react/jsx-key */
import type { NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import SummaryStyle from "../components/Summary/Summary.style";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>NextJS Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <SummaryStyle.Container>
          <SummaryStyle.Title>Welcome Aboard</SummaryStyle.Title>
          <Link href={"/static-generation"}>
            <a>Static Generation</a>
          </Link>
          <Link href={"/static-generation/with-data"}>
            <a>Static Generation With Data</a>
          </Link>
          <Link href={"/static-generation/without-data"}>
            <a>Static Generation Without Data</a>
          </Link>
          <Link href={"/server-side-rendering"}>
            <a>Server Side Rendering</a>
          </Link>
        </SummaryStyle.Container>
      </main>
    </div>
  );
};

export default Home;
